# Generated by Django 4.1.6 on 2023-02-14 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dishes',
            new_name='Waiter',
        ),
    ]
