# Generated by Django 4.1.6 on 2023-02-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0002_rename_dishes_waiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiter',
            name='provenance',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='waiter',
            name='years',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
